language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
notifications:
  email:
    on_success: never
    on_failure: always
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: codydevbox@gmail.com
  api_key:
    secure: Slg1f6I8IJI/debyAQvQzDP55FEfA7CAXHF1a4KfOFQhebXhrg2RfuF9m3ZdawCKXcGUm54CcJLYbN5bcpoPt5tPtSeGoBPPAI888n1+bWqpukU/UldIrqKNq8Yqd6/CiWGFUCym5/I1FiBagy3/0RxfocXruQgMwDG3e3yQYKhvU/9bSGJCMCNmlNA7TQZCuFHk3IR0Qrb34h3e1CiDVFkhDB5UE1XJJIOnmv5S4hFMxXmdq7+JPioIQ0Sxx8ZEn3NbKMd+Xn3hvBOJyFkFQDJFwlxVHVnmbWJFWCWBsfuu1eLnlcU2/gHhXEfy2uQQZJClVslbHBYjVgS7Pir1kNacmdiO5bcvvKMmz8SljtDPjtRVUEYevs4L33ASPFOAX5hqkO0bqySHLYSB9XBD/kgLGl22ZXsR3zY1XMyzbvlr6qaIWjiOIgBbUFQYbG8XeMnnTBrR90stK25zKzoqPuOr5+cdHcJfk69k577GqG+Jql7wCrvEiM0I5hn3zxitGiSJ2EezPbckZvG5A3kalrCpgsUw7dEZmrjcQOQ1hKPgbiikGOB8m8opAIbpBS9VTxlYlxarSYKEfKsPtCixabBAANNJG6vBojtCWvLrFZHKTu9m4jY2No4ibJPBNyIMKBwxKd0iMzRMONIZqnKwDHRt+dov3tc0thSsEanJKOw=
  on:
    branch: master
    repo: codyjdalton/default-response
